### ISSUE TITLE
Add photutils

### ISSUE THREAD

**Issue by danielballan** [nsls-ii-forge/analysis-feedstock#23]
This was requested by Tatiana.

**Comment by mrakitin** [comment]
Oh, right, we need that.

**Comment by mrakitin** [comment]
Building via https://github.com/nsls-ii-forge/photutils-feedstock/pull/1.

**Comment by mrakitin** [comment]
Closed via https://github.com/nsls-ii-forge/analysis-feedstock/pull/24.
