### ISSUE TITLE
Add packages requested by BMM.

### ISSUE THREAD

**Issue by danielballan** [nsls-ii-forge/analysis-feedstock#31]
Some of these are already present, but in any case this was the list requested.

```
slackclient
redis
requests
pillow
inflection
ansiwrap
lmfit
h5py
sklearn
```

**Comment by danielballan** [comment]
Some of these (slackclient, redis) _might_ belong better in just the collection environment, but I could think of reasons that people might want to use them from an analysis context as well.

**Comment by danielballan** [comment]
From @stuartcampbell:

> We should probably make sure slack_sdk is packaged as well.  As this has replaced slackclient, which has been moved into a maintenance mode by slack.

**Comment by bruceravel** [comment]
As I said via email, I was mistaken in requesting slackclient.  I actually am using the Slack python dev kit.  So _that_ should be installed, not slackclient.

Just another user with poorly articulated, constantly-changing needs....

**Comment by leofang** [comment]
Oops @bruceravel I didn't notice your reply here. #32 just went in which had `slackclient` included. Could you give me the package name and/or a url to it, so that I know exactly which dev kit you're referring to? Thanks.

**Comment by bruceravel** [comment]
Hmmmm..... @leofang , maybe I'm confused or maybe I didn't understand the point Stuart was making in his email the other day to dama@bnl.gov.....

I guess that this (https://pypi.org/project/slackclient/) and this (https://github.com/slackapi/python-slack-sdk) are the same thing.

So, I guess I don't understand what distinction Stuart was making when he said "We should probably make sure slack_sdk is packaged as well.  As this has replaced slackclient, which has been moved into a maintenance mode by slack."  Seems to me that everyone is talking about the same package.  Is that right...? :confused:

**Comment by leofang** [comment]
Ahh thanks @bruceravel for the pointers. It's clear to me now. So there're `slackclient` and `slack_sdk` on PyPI and can be pip-installed, and yes currently they are "the same package". But the former is under maintenance mode now, which is basically to say it's deprecated and succeeded by the latter. So any future improvements/enhancements/etc will only be added to the latter. I think they offer a migration guide for its users: https://slack.dev/python-slack-sdk/v3-migration/. 

For the time being, though, I think we should have both `slackclient` and `slack_sdk` included in our conda recipe to help you start the migration. I will do this shortly.

**Comment by leofang** [comment]
...I think for `slack_sdk` we should wait until it's actually out. `slack_sdk` is currently on v3.0rc1. (And the v2.x series refers to `slackclient`.)

**Comment by leofang** [comment]
@bruceravel @danielballan I opened #33 to track this request and am closing the preset issue.

**Comment by bruceravel** [comment]
Thankfully, you understand the situation better than I do, @leofang! :smiley:

**Comment by mrakitin** [comment]
Good summary. I think it will be handled by the same conda package `slackclient` starting with v3 (which was released 3 days ago).
